// PROVINCES
const GET_PROVINCES = "GET_PROVINCES";
const GET_PROVINCES_PENDING = "GET_PROVINCES_PENDING";
const GET_PROVINCES_FULFILLED = "GET_PROVINCES_FULFILLED";
const GET_PROVINCES_REJECTED = "GET_PROVINCES_REJECTED";

// LOCATIONS
const GET_LOCATIONS = "GET_LOCATIONS";
const GET_LOCATIONS_PENDING = "GET_LOCATIONS_PENDING";
const GET_LOCATIONS_FULFILLED = "GET_LOCATIONS_FULFILLED";
const GET_LOCATIONS_REJECTED = "GET_LOCATIONS_REJECTED";

// FORM
const POST_FORM = "POST_FORM";
const POST_FORM_PENDING = "POST_FORM_PENDING";
const POST_FORM_FULFILLED = "POST_FORM_FULFILLED";
const POST_FORM_REJECTED = "POST_FORM_REJECTED";

export {
  GET_PROVINCES,
  GET_PROVINCES_PENDING,
  GET_PROVINCES_FULFILLED,
  GET_PROVINCES_REJECTED,
  GET_LOCATIONS,
  GET_LOCATIONS_PENDING,
  GET_LOCATIONS_FULFILLED,
  GET_LOCATIONS_REJECTED,
  POST_FORM,
  POST_FORM_PENDING,
  POST_FORM_FULFILLED,
  POST_FORM_REJECTED
};
